// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://okazripbgrnqzvfqucnu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9rYXpyaXBiZ3JucXp2ZnF1Y251Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE1NDQ2OTUsImV4cCI6MjA2NzEyMDY5NX0.96II04ytHD6yw0u2DU4PhSJZeg3YRhxMNyHY4DkDSuA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});